### ISSUE TITLE
登陆报错

### ISSUE THREAD

**Issue by southcat** [wyq2214368/remove-water-mark-server#10]
{
    "message": "Undefined index: unionId",
    "exception": "ErrorException",
    "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/app/Http/Controllers/Auth/LoginController.php",
    "line": 55,
    "trace": [
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/app/Http/Controllers/Auth/LoginController.php",
            "line": 55,
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "function": "login",
            "class": "App\\Http\\Controllers\\Auth\\LoginController",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 219,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 176,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 681,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 130,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/app/Http/Middleware/RedirectIfAuthenticated.php",
            "line": 25,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "App\\Http\\Middleware\\RedirectIfAuthenticated",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
            "line": 59,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 105,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 683,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 658,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 624,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 613,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 170,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 130,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 63,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 105,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 145,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 110,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/public/index.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/server.php",
            "line": 21,
            "function": "require_once"
        }
    ]
}

**Comment by wyq2214368** [comment]
"file": "/www/Recycle_bin/_bt_www_bt_wwwroot_bt_remove-water-mark-server-master_t_1639996111.6647003/app/Http/Controllers/Auth/LoginController.php",
"line": 55,

可以到这个文件55行附近打印看一下具体的返回数据都有哪些。我这边看了下是有unionid的，都正常。

**Comment by southcat** [comment]
文件里面有这个返回数据，但是好像新注册的小程序现在无法使用usergetinfo获取到这个信息了

**Comment by southcat** [comment]
问题找到了 还需要绑定一下开放平台的账号 不绑定的话获取不到unionid

**Comment by wyq2214368** [comment]
https://github.com/wyq2214368/remove-water-mark-server/blob/master/app/Http/Controllers/Auth/LoginController.php#L55
默认去掉了unionid，如需使用可自行处理
