### ISSUE TITLE
这个服务端接口被盗用怎么办

### ISSUE THREAD

**Issue by mmat001** [wyq2214368/remove-water-mark-server#4]
能防盗链吗

**Comment by wyq2214368** [comment]
> 能防盗链吗

需要微信登陆换token的，请求接口没有token是会认证失败的，基本不存在0成本盗用问题

**Comment by mmat001** [comment]
> > 能防盗链吗
> 
> “防盗链”一般指图片，项目中不涉及此类问题。
> 
> 解答标题问题：需要微信登陆换token的，请求接口没有token是会认证失败的，基本不存在0成本盗用问题

如果我想做几个小程序，能用同一个接口吗

**Comment by wyq2214368** [comment]
> > > 能防盗链吗
> > 
> > 
> > “防盗链”一般指图片，项目中不涉及此类问题。
> > 解答标题问题：需要微信登陆换token的，请求接口没有token是会认证失败的，基本不存在0成本盗用问题
> 
> 如果我想做几个小程序，能用同一个接口吗

不能直接使用，由于不同小程序的appkey和secret不同，接入多个都话需要一定改造。

如果不需要用户认证，只想对任意请求都解析水印，只需要去掉认证中间件即可，这样成本非常小。
