### ISSUE TITLE
video-parse 报错

### ISSUE THREAD

**Issue by IMRUMI** [wyq2214368/remove-water-mark-server#5]
"message": "Client error: `GET https://www.iesdouyin.com/web/api/v2/aweme/iteminfo?item_ids=6798723415604792584` resulted in a `444 ` response",
    "exception": "GuzzleHttp\\Exception\\ClientException",
    "file": "/root/remove-water-mark-server/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php",
    "line": 113,

**Comment by wyq2214368** [comment]
更换small-tool的版本到dev-master即可解决，目前该依赖包的release版本中最新的1.3.8也是去年的了，而最新的master代码作者有修复，试着是ok的。
`composer require smalls/video-tools:dev-master`
