### ISSUE TITLE
找不到文件

### ISSUE THREAD

**Issue by GotoFit** [wyq2214368/remove-water-mark-server#7]
require __DIR__.'/vendor/autoload.php'; 这个路径找不到

**Comment by wyq2214368** [comment]
> require **DIR**.'/vendor/autoload.php'; 这个路径找不到

执行composer install后才有vendor目录

**Comment by Faker-21** [comment]
我用的是 Apache  我该如何添加下载url配置

**Comment by wyq2214368** [comment]
> 我用的是 Apache 我该如何添加下载url配置

这是另一个问题了是吧，vendor已经解决了。建议新开issue提问。
另外Apache配置我不确定，可以自行查一下。或提个新issue等其他同学回复
